@startuml enums
' Centralized enum definitions for Talisman OS diagram

enum RegionType {
  OUTER_REGION
  MIDDLE_REGION
  INNER_REGION
  CROWN_OF_COMMAND
}

enum SpaceType {
  NORMAL
  CITY
  VILLAGE
  CHAPEL
  GRAVEYARD
  DESERT
  FOREST
  HILLS
  PLAINS
}

enum PlayerState {
  WAITING
  ROLLING
  MOVING
  ENCOUNTERING
  COMBAT
  SHOPPING
  STUNNED
}

enum CharacterType {
  WARRIOR
  WIZARD
  THIEF
  PRIEST
  DWARF
  ELF
  ASSASSIN
  MINSTREL
}

enum FollowerType {
  HUMAN
  ANIMAL
  SPIRIT
  MAGICAL
}

enum CardType {
  ADVENTURE
  SPELL
  ENEMY
  STRANGER
  OBJECT
  PLACE
  EVENT
}

enum EffectDuration {
  INSTANT
  ONE_TURN
  PERMANENT
  CONDITIONAL
}

' Encounter categories used by AdventureCard
enum EncounterType {
  DRAW
  STRANGER
  ENEMY
  PLACE
  EVENT
  SHOP
  SPECIAL
}

@enduml